os:
  - linux
  - osx
  - windows

language:
  - python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "3.10"
  - "3.10-dev"
  - "3.11"
  - "3.11-dev"
  - "nightly"  # nightly build
  # PyPy versions
  # - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.9,  PyPy 7.3.1

jobs:
  allow_failures:
    - os: osx
  include:

    - name: "Python 3.5.0 on Xenial Linux"
      os: linux
      python: 3.5
      env: TOXENV=py35

    - name: "Python 3.6.0 on Xenial Linux"
      os: linux
      python: 3.6
      env: TOXENV=py36

    - name: "Python 3.7.0 on Xenial Linux"
      os: linux
      python: 3.7
      env: TOXENV=py37

    - name: "Python 3.8.0 on Xenial Linux"
      os: linux
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      env: TOXENV=py38

    - name: "Python 3.10.0 on Xenial Linux"
    - os: linux
      python: 3.10
      env: TOXENV=py310

    - name: "Python 3.11.0 on Xenial Linux"
      os: linux
      python: 3.11
      env: TOXENV=py311

#################################################

    - name: "Python 3.6.10 on FreeBSD"
      os: freebsd
      language: python

    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


install:
  - pip3 install --upgrade pip
  - pip install -q selenium==$SELENIUM_VERSION
  - python setup.py -q install
  # - pip install -r requirements.txt
  # - pip install .

script: pytest tests/selenium/browsers

addons:
   firefox: latest
   chrome: stable

env:
  - SELENIUM_VERSION=3.141.0
  - SELENIUM_VERSION=4.5.0